# Generated by Django 3.1 on 2020-08-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_general', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cluster',
            new_name='Customer',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_created', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_test_general.customer')),
            ],
        ),
    ]
