# Generated by Django 3.1 on 2020-08-19 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_general', '0003_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(max_length=50)),
                ('long_text', models.TextField(blank=True, default='...', max_length=500)),
                ('user_created', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_test_general.cluster')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_test_general.customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_test_general.project')),
            ],
        ),
    ]
