# Generated by Django 3.1 on 2020-08-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_general', '0005_auto_20200819_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colorname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorname', models.CharField(max_length=100)),
            ],
        ),
    ]
