# Generated by Django 3.1 on 2020-08-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_general', '0007_auto_20200822_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetTweaksExamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
