# Generated by Django 3.1 on 2020-08-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_general', '0009_widgettweaksexamples_date_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextareaInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('user_created', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
