# Generated by Django 3.1 on 2020-08-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_general', '0010_textareainput'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('object_a', models.CharField(max_length=50)),
                ('amount_a', models.IntegerField(default=0)),
                ('object_b', models.CharField(max_length=50)),
                ('amount_b', models.IntegerField(default=0)),
                ('object_c', models.CharField(max_length=50)),
                ('amount_c', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='textareainput',
            options={'ordering': ['-id']},
        ),
    ]
