# Generated by Django 3.1 on 2020-08-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_general', '0012_auto_20200830_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvgroupmodel',
            name='object_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='csvgroupmodel',
            name='object_b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='csvgroupmodel',
            name='object_c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
