# Generated by Django 3.1 on 2020-08-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_general', '0013_auto_20200830_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_filter_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Diverse', 'Diverse')], max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
