# Generated by Django 3.1 on 2020-09-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_general', '0014_table_filter_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportExamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Diverse', 'Diverse')], max_length=50)),
            ],
        ),
    ]
