# Generated by Django 3.1 on 2020-09-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_general', '0015_transportexamples'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeFilteringExamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
    ]
